name: Publish to Maven Central

on:
    push:
        branches:
            - master
            - publish--maven

jobs:
    publish:
        name: Publish
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up JDK
              uses: actions/setup-java@v2
              with:
                  java-version: '11'  # Adjust as per your JDK version requirement

            - name: Publish to Maven Repository
              env:
                  MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
                  MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
              run: ./gradlew publish  # Run Gradle task to publish artifacts

            - name: Verify artifacts
              run: ./gradlew check  # Optional: Run any verification steps after publishing
