name: Publish to Maven Central

on:
    push:
        branches:
            - master
            - publish--maven

jobs:
    Test:
        environment: prod
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v4
            -   name: Restore gradle.properties
                env:
                    GRADLE_PROPERTIES: ${{ secrets.GRADLE_PROPERTIES }}
                shell: bash
                run: |
                    mkdir -p ~/.gradle/
                    echo "GRADLE_USER_HOME=${HOME}/.gradle" >> $GITHUB_ENV
                    echo "${GRADLE_PROPERTIES}" > ~/.gradle/gradle.properties
            -   uses: actions/setup-java@v2
                with:
                    java-version: '17'
                    distribution: 'temurin'
            -   run: chmod +x gradlew
            -   run: ./gradlew test
                env:
                    RINGCENTRAL_SERVER_URL: ${{ secrets.RINGCENTRAL_SERVER_URL }}
                    RINGCENTRAL_CLIENT_ID: ${{ secrets.RINGCENTRAL_CLIENT_ID }}
                    RINGCENTRAL_CLIENT_SECRET: ${{ secrets.RINGCENTRAL_CLIENT_SECRET }}
                    RINGCENTRAL_JWT_TOKEN: ${{ secrets.RINGCENTRAL_JWT_TOKEN }}
                    RINGCENTRAL_SENDER: ${{ secrets.RINGCENTRAL_SENDER }}
                    RINGCENTRAL_RECEIVER: ${{ secrets.RINGCENTRAL_RECEIVER }}
    publish:
        name: Publish
        needs: Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up JDK
              uses: actions/setup-java@v2
              with:
                  java-version: '11'  # Adjust as per your JDK version requirement

            - name: Publish to Maven Repository
              env:
                  MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
                  MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
              run: ./gradlew publish  # Run Gradle task to publish artifacts

            - name: Verify artifacts
              run: ./gradlew check  # Optional: Run any verification steps after publishing
